[colors]
primary = { background = "0x2E3440", foreground = "0xD8DEE9" }
cursor = { text = "0x2E3440", cursor = "0xD8DEE9" }
vi_mode_cursor = { text = "0x2E3440", cursor = "0x88C0D0" }
selection = { text = "0x2E3440", background = "0x4C566A" }
indexed_colors = []

[colors.normal]
black = "0x3B4252"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors.bright]
black = "0x4C566A"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xECEFF4"

[font]
size = 8.0
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
